from cs1graphics import *
import time
WIDTH = 900
HIGHT = 600
BOARD_COLOR = "skyblue"
our_village = Canvas(WIDTH, HIGHT, BOARD_COLOR, "OUR VILLAGE")
GROUND = Rectangle(WIDTH, 270, Point(450, 500))
GROUND.setFillColor("green")
GROUND.setBorderWidth(2)
# SUN
def sun_obj():
    SUN = Layer()
    sun = Circle(30, Point(10,40))
    sun.setFillColor("yellow")
    sun.setBorderWidth(0)
    SUN.add(sun)
    ray = Path(Point(40, 60), Point(60, 75))
    ray.setBorderWidth(3)
    ray.setBorderColor("yellow")
    SUN.add(ray)
    ray2 = ray.clone()
    ray3 = ray.clone()
    ray2.move(5,-30)
    ray2.rotate(-60)
    ray3.move(-25, 15)
    ray3.rotate(40)
    SUN.add(ray3)
    SUN.add(ray2)
    return SUN
our_village.add(sun_obj())
our_village.add(GROUND)
hen = Layer()
body = Ellipse(50, 90, Point(200, 100))
wing = Circle(23, Point(205, 116))
wing.setFillColor("lightyellow")
wing.setBorderColor("yellow")
body.setFillColor("lightyellow")
body.setBorderColor("yellow")
leg = Path(Point(190, 143), Point(190, 155))
leg.setBorderWidth(4)
leg.setBorderColor("darkgray")
leg_2 = leg.clone()
leg_2.move(7,0)
# l = Path(Point(190, 160), Point(180, 170))
# l2 = Path(Point(190, 160), Point(180, 170))
hair = Path(Point(195, 55), Point(195, 45))
hair.setBorderColor("red")
hair.setBorderWidth(4)
hair_2 = Path(Point(200, 55), Point(200, 45))
hair_2.setBorderColor("red")
hair_2.setBorderWidth(4)
noise = Polygon(Point(177, 80), Point(177, 90), Point(166, 85))
noise.setFillColor("orange")
noise.setBorderWidth(0)
eye = Ellipse(8, 13, Point(190, 75))
eye.setFillColor("black")
hen.add(body)
hen.add(wing)
hen.add(leg)
hen.add(leg_2)
hen.add(hair)
hen.add(hair_2)
hen.add(noise)
hen.add(eye)
child_body = Ellipse(25, 45, Point(300, 200))
child_wing = Circle(11, Point(303, 208))
child_wing.setFillColor("yellow")
child_wing.setBorderColor("orange")
child_body.setFillColor("yellow")
child_body.setBorderColor("yellow")
child_noise = noise.clone()
child_noise.scale(0.6)
child_noise.move(112, 107)
child_eye = eye.clone()
child_eye.scale(0.5)
child_eye.move(106,111)
child_hair = hair.clone()
child_hair.move(103, 124)
child_hair.scale(0.5)
child_hair_2 = child_hair.clone()
child_hair_2.move(3, 0)
child_leg = Path(Point(300, 223), Point(300, 230))
child_leg.setBorderWidth(3)
child_leg.setBorderColor("gray")
child_leg_2 = child_leg.clone()
child_leg_2.move(-5,0)
child = Layer()
# child.add()
child.add(child_body)
child.add(child_wing)
child.add(child_noise)
child.add(child_eye)
child.add(child_hair)
child.add(child_hair_2)
child.add(child_leg)
child.add(child_leg_2)
child.moveTo(380, 220)
child_2 = child.clone()
child_2.move(50, 0)
our_village.add(hen)
hen.moveTo(400,300)
our_village.add(child)
our_village.add(child_2)
def move_forward(hen, child, child_2, number_of_move):
    for m in range(number_of_move):
        hen.move(-1,0)
        child.move(-1,0)
        time.sleep(0.0003)
        child_2.move(-1,0)
    for k in range(number_of_move):
        sun = sun_obj()
        sun.move(1,0)
move_forward(hen, child,child_2, 750)
