from cs1graphics import *
BOARD_WIDTH = 1500
BOARD_HEIGHT = 700
def get_triangle(width, height, center=Point(0, 0), fillColor=None):
    center_x, center_y = center.get()
    top_point = Point(center_x, center_y - height // 2)
    left_point = Point(center_x - width // 2, center_y + height // 2)
    right_point = Point(center_x + width // 2, center_y + height // 2)
    triangle = Polygon(top_point, left_point, right_point)
    if fillColor is not None:
        triangle.setBorderWidth(0)
        triangle.setFillColor(fillColor)
    return triangle
def get_tree(rootPoint, stem_width, stem_height, branches=5):
    tree = Layer()
    root_x, root_y = rootPoint.get()
    stem = Rectangle(stem_width, stem_height, Point(root_x, root_y - stem_height // 2))
    stem.setBorderWidth(0)
    stem.setFillColor("brown")
    tree.add(stem)
    for i in range(branches):
        branch = get_triangle(
            100 + i * 30,
            100 - i * 10,
            Point(  root_x, (root_y - ((branches - i) * (45)) - stem_height + 20)   ),"darkgreen",)
        tree.add(branch)
    return tree
def plant_trees(points, board, stem_width=50, stem_height=150):
    for point in points:
        tree = get_tree(point, stem_width, stem_height)
        board.add(tree)
def get_house():
    hourse = Layer()
    ceil = get_triangle(200, 100, Point(1000, 330))
    ceil.setFillColor("black")
    body = Rectangle(180, 120, Point(1000, 440))
    body.setBorderWidth(5)
    body.setFillColor("brown")
    door = Rectangle(80, 100, Point(1040, 450))
    door.setBorderWidth(5)
    door.setFillColor("darkgrey")
    window = Rectangle(50, 50, Point(955, 430))
    window.setBorderWidth(3)
    window.setFillColor("white")
    min_window_2 = Rectangle(25, 25, Point(967, 418))
    min_window_1 = Rectangle(25, 25, Point(942, 418))
    min_window_3 = Rectangle(25, 25, Point(942, 443))
    min_window_4 = Rectangle(25, 25, Point(967, 443))
    chimney = Rectangle(40, 100, Point(950, 330))
    chimney.setFillColor("sandybrown")
    chimney.setBorderWidth(5)
    hourse.add(chimney)
    hourse.add(ceil)
    hourse.add(body)
    hourse.add(door)
    hourse.add(window)
    hourse.add(min_window_1)
    hourse.add(min_window_2)
    hourse.add(min_window_3)
    hourse.add(min_window_4)
    return hourse
def get_human():
    human = Layer()
    head = Circle(25, Point(750, 350))
    head.setFillColor("sandybrown")
    body = Ellipse(50, 80, Point(750, 415))
    body.setFillColor("pink")
    hand = Path(Point(690, 350), Point(750, 400), Point(810, 350))
    hand.setBorderWidth(5)
    hand.setBorderColor("orange")
    leg = Rectangle(20, 70, Point(750, 470))
    leg.setBorderWidth(5)
    leg.setBorderColor("orange")
    left_eye = Circle(2, Point(740, 340))
    left_eye.setBorderWidth(3)
    right_eye = Circle(2, Point(760, 340))
    right_eye.setBorderWidth(3)
    mouth = Ellipse(10, 5, Point(750, 360))
    human.add(head)
    human.add(left_eye)
    human.add(right_eye)
    human.add(mouth)
    human.add(hand)
    human.add(leg)
    human.add(body)
    return human
def get_bubble():
    bubble = Layer()
    text = Text("It's Beautiful day!", 12, Point(650, 270))
    thought = Ellipse(140, 75, Point(650, 270))
    thought.setBorderWidth(2)
    min_buble = thought.clone()
    min_buble.scale(0.25)
    min_buble.move(50, 50)
    bubble.add(text)
    bubble.add(thought)
    bubble.add(min_buble)
    return bubble
screen = Canvas(w=BOARD_WIDTH, h=BOARD_HEIGHT, bgColor="skyblue", title="Beautiful Day")
cloud = Layer()
min_cloud = Circle(50, Point(300, 300))
min_cloud.setFillColor("white")
min_cloud.setBorderWidth(0)
single_cloud = Ellipse(40, 10, Point(285, 300))
single_cloud.setFillColor("white")
single_cloud.setBorderWidth(0)
single_cloud_2 = Ellipse(40, 20, Point(285, 460))
single_cloud_2.setFillColor("white")
single_cloud_2.setBorderWidth(0)
single_cloud_3 = Ellipse(60, 30, Point(555, 460))
single_cloud_3.setFillColor("white")
single_cloud_3.setBorderWidth(0)
screen.add(single_cloud_2)
screen.add(single_cloud)
screen.add(single_cloud_3)
min_cloud_2 = min_cloud.clone()
min_cloud_2.setFillColor("white")
min_cloud_3 = min_cloud_2.clone()
min_cloud_3.setFillColor("white")
min_cloud_4 = min_cloud_3.clone()
min_cloud_4.setFillColor("white")
min_cloud_5 = min_cloud_4.clone()
min_cloud_5.setFillColor("white")
min_cloud_6 = min_cloud_5.clone()
min_cloud_6.setFillColor("white")
min_cloud_7 = min_cloud_5.clone()
min_cloud_8 = min_cloud_7.clone()
min_cloud_8.setFillColor("white")
min_cloud_9 = min_cloud_8.clone()
min_cloud_9.setFillColor("white")
min_cloud_2.move(-120, 10)
min_cloud_3.move(90, 30)
min_cloud_4.move(100, 70)
min_cloud_5.move(50, 150)
min_cloud_6.move(22, 80)
min_cloud_7.move(-70, 50)
min_cloud_8.move(-100, 100)
min_cloud_9.move(-45, 136)
cloud.add(min_cloud)
cloud.add(min_cloud_2)
cloud.add(min_cloud_3)
cloud.add(min_cloud_4)
cloud.add(min_cloud_5)
cloud.add(min_cloud_6)
cloud.add(min_cloud_7)
cloud.add(min_cloud_8)
cloud.add(min_cloud_9)
screen.add(cloud)
cloud.move(-100, -200)
# clone cloud layer to other cloud
cloud_2 = cloud.clone()
cloud_2.move(550, 500)
screen.add(cloud_2)
cloud_3 = cloud.clone()
cloud_3.scale(0.7)
cloud_3.move(10, 400)
cloud_4 = cloud.clone()
cloud_4.scale(0.5)
cloud_4.move(800, 300)
cloud_5 = cloud_4.clone()
cloud_5.scale(0.7)
cloud_5.move(100, 200)
cloud.add(cloud_5)
screen.add(cloud_3)
screen.add(cloud_4)
ground = Rectangle(BOARD_WIDTH, 200, Point(BOARD_WIDTH // 2, BOARD_HEIGHT - 100))
ground.setBorderWidth(0)
ground.setFillColor("darkgreen")
ground.setDepth(0)
screen.add(ground)
TREE_POINTS = [  Point(100, 520),Point(300, 520),Point(500, 520),Point(1200, 520),Point(1400, 520),] 
plant_trees(TREE_POINTS, screen)
hourse = get_house()
human_with_bubble = Layer()
human = get_human()
bubble = get_bubble()
human_with_bubble.add(human)
human_with_bubble.add(bubble)
screen.add(hourse)
screen.add(human_with_bubble)
for i in range(350):
    human_with_bubble.move(5, 0)
    x, y = human_with_bubble.getReferencePoint().get()
    print x, y
    if x > 950:
        human_with_bubble.moveTo(-750, y)
